// Class for Employee
export class Employee {
  _id?: string; // Place holder for the _id field generated by mongoDB
  firstName: string;
  lastName: string;
  hireDate: string;
  role: string;
  favoriteJoke?: string;
  favoriteQuote?: string;
}
